<a href="https://colab.research.google.com/github/myjjojjojjo/Lesson/blob/main/20230329_%EA%B8%B0%EC%B4%88%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
s='WiseInCompany'
s1="WiseInCompany"
s2='''WiseInCompany'''
s3="123"

In [4]:
print(s)
print(s1)
print(s2)
print(s3)

WiseInCompany
WiseInCompany
WiseInCompany
123


In [6]:
print(type(s3))

<class 'str'>


In [7]:
s1+s2

'WiseInCompanyWiseInCompany'

In [8]:
s1*3

'WiseInCompanyWiseInCompanyWiseInCompany'

In [10]:
a="Wise In Company"

In [13]:
print(a[2])
print(a[0:4])
print(a[0:5])

s
Wise
Wise 


In [16]:
b=[1,2,3,4,5]
b.append(100)
print(b)
del b[1]

[1, 2, 3, 4, 5, 100]


In [17]:
c={"Kim":90, "Jeong":80, "Park":75}
c["Kim"]

90

In [18]:
c["Jeong"]=95
print(c)

{'Kim': 90, 'Jeong': 95, 'Park': 75}


In [19]:
print(c.keys())

dict_keys(['Kim', 'Jeong', 'Park'])


In [20]:
print(c.values())

dict_values([90, 95, 75])


In [28]:
money=2000

if money >= 3000:
  print("bus")

elif money >= 5000:
  print("train")

else :
  print('walk')
 


walk


In [30]:
sum=0
for i in range(11):
  sum=sum+i
print(sum)

55


In [32]:
import numpy as np
v=np.array([1,2,3,4])
print(v)

[1 2 3 4]


In [39]:
v1=np.arange(5).reshape(1,5)
print(v1)

[[0 1 2 3 4]]


In [40]:
v2=np.arange(1,5).reshape(4,1)
print(v2)

[[1]
 [2]
 [3]
 [4]]


In [42]:
v3=np.arange(1,13)
v3
print(v3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [62]:
v4=v3.reshape(4,3,1)
print(v4)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [66]:
d=np.arange(1,5)
d1=d.reshape(1,2,2, order='F')
print(d1)

[[[1 3]
  [2 4]]]


In [68]:
import pandas as pd

In [72]:
df=pd.read_csv('Testing_set_whitewine.csv')
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               5.8             0.340         0.21            6.60      0.040   
1               6.5             0.350         0.36            0.80      0.034   
2               7.0             0.290         0.26            1.60      0.044   
3               6.4             0.280         0.29            1.60      0.052   
4               7.4             0.200         0.37           16.95      0.048   
...             ...               ...          ...             ...        ...   
1465            4.8             0.170         0.28            2.90      0.030   
1466            5.6             0.255         0.57           10.70      0.056   
1467            6.1             0.210         0.19            1.40      0.046   
1468            8.5             0.150         0.49            1.50      0.031   
1469            7.5             0.240         0.31           13.10      0.050   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    50.0                 167.0  0.99410  3.29       0.62   
1                    32.0                 111.0  0.98942  3.11       0.50   
2                    12.0                  87.0  0.99230  3.08       0.46   
3                    34.0                 127.0  0.99290  3.48       0.56   
4                    43.0                 190.0  0.99950  3.03       0.42   
...                   ...                   ...      ...   ...        ...   
1465                 22.0                 111.0  0.99020  3.38       0.34   
1466                 66.0                 171.0  0.99464  3.25       0.61   
1467                 51.0                 131.0  0.99184  3.22       0.39   
1468                 17.0                 122.0  0.99320  3.03       0.40   
1469                 26.0                 180.0  0.99884  3.05       0.53   

      alcohol  
0        10.0  
1        12.1  
2        10.5  
3        10.5  
4         9.2  
...       ...  
1465     11.3  
1466     10.4  
1467     10.5  
1468     10.3  
1469      9.1  

[1470 rows x 11 columns]

In [74]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            5.8              0.34         0.21            6.60      0.040   
1            6.5              0.35         0.36            0.80      0.034   
2            7.0              0.29         0.26            1.60      0.044   
3            6.4              0.28         0.29            1.60      0.052   
4            7.4              0.20         0.37           16.95      0.048   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 50.0                 167.0  0.99410  3.29       0.62   
1                 32.0                 111.0  0.98942  3.11       0.50   
2                 12.0                  87.0  0.99230  3.08       0.46   
3                 34.0                 127.0  0.99290  3.48       0.56   
4                 43.0                 190.0  0.99950  3.03       0.42   

   alcohol  
0     10.0  
1     12.1  
2     10.5  
3     10.5  
4      9.2

In [75]:
df[:3]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            5.8              0.34         0.21             6.6      0.040   
1            6.5              0.35         0.36             0.8      0.034   
2            7.0              0.29         0.26             1.6      0.044   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 50.0                 167.0  0.99410  3.29       0.62   
1                 32.0                 111.0  0.98942  3.11       0.50   
2                 12.0                  87.0  0.99230  3.08       0.46   

   alcohol  
0     10.0  
1     12.1  
2     10.5

In [80]:
df[['fixed acidity']][:3]

fixed acidity
0            5.8
1            6.5
2            7.0

In [83]:
df[df.columns[[0,2,4]]][11:16]

fixed acidity  citric acid  chlorides
11            5.7         0.22      0.044
12            5.9         0.23      0.037
13            6.9         0.32      0.036
14            6.1         0.45      0.094
15            6.7         0.24      0.044

In [85]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1470.000000       1470.000000  1470.000000     1470.000000   
mean        6.841735          0.280680     0.335245        6.325238   
std         0.876609          0.103621     0.126326        5.261487   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.000000   
75%         7.300000          0.330000     0.380000        9.600000   
max        10.700000          0.965000     1.230000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1470.000000          1470.000000           1470.000000  1470.000000   
mean      0.046160            34.936054            136.888435     0.993975   
std       0.023939            17.823839             42.223325     0.003153   
min       0.009000             3.000000             10.000000     0.987400   
25%       0.035000            23.000000            108.000000     0.991700   
50%       0.043000            33.000000            132.000000     0.993620   
75%       0.050000            45.000000            166.000000     0.995900   
max       0.301000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol  
count  1470.000000  1470.000000  1470.000000  
mean      3.186864     0.487374    10.538846  
std       0.150717     0.114600     1.224267  
min       2.770000     0.250000     8.500000  
25%       3.080000     0.400000     9.500000  
50%       3.170000     0.470000    10.400000  
75%       3.280000     0.540000    11.400000  
max       3.800000     1.060000    14.000000

In [90]:
df.loc[0:5, df.columns[[0,2,4]]]

fixed acidity  citric acid  chlorides
0            5.8         0.21      0.040
1            6.5         0.36      0.034
2            7.0         0.26      0.044
3            6.4         0.29      0.052
4            7.4         0.37      0.048
5            6.0         0.49      0.048

In [93]:
df.iloc[0:5, :1]

fixed acidity
0            5.8
1            6.5
2            7.0
3            6.4
4            7.4

In [97]:
len(df.columns)

11

In [98]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')

In [102]:
df.rename(columns={'fixed acidity': 'acidity'}, inplace=True)
df.columns

Index(['acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')

In [105]:
df['growth']=df['density']/df['pH']
print(df.columns)
len(df.columns)

Index(['acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'growth'],
      dtype='object')


12

In [110]:
df['pH'].value_counts()

3.14    54
3.24    52
3.08    52
3.16    48
3.15    46
        ..
3.61     1
3.58     1
3.64     1
3.68     1
3.66     1
Name: pH, Length: 87, dtype: int64

In [111]:
df['alcohol'].value_counts()

9.200000     71
9.400000     68
9.000000     58
10.500000    54
9.500000     53
             ..
10.966667     1
8.500000      1
13.550000     1
12.333333     1
13.050000     1
Name: alcohol, Length: 78, dtype: int64